### ISSUE TITLE
'No naming context bound to this class loader' error when using realms as authentication method

### ISSUE THREAD

**Issue by teemu47** [jsimone/webapp-runner#118]
Hi,

App works fine when deployed to Tomcat server. With webapp-runner an error occurs when app is trying to connect to database for authentication.

Tried with and without --context-xml flag which was picked up at startup: `Using context config: /src/main/webapp/META-INF/context.xml`

Stacktrace:
```
org.apache.catalina.realm.DataSourceRealm open
SEVERE: Exception performing authentication
javax.naming.NamingException: No naming context bound to this class loader
	at org.apache.naming.ContextBindings.getClassLoader(ContextBindings.java:268)
	at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:380)
	at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:255)
	at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:188)
	at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:153)
	at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:264)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:572)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

App is using LockOutRealm, DatasSourceRealm and SecretKeyCredentialHandler. Here's the context-xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<Context>
    <WatchedResource>WEB-INF/web.xml</WatchedResource>

    <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.DataSourceRealm"
               localDataSource="true"
               dataSourceName="jdbc/authority"
               userTable="users"
               userNameCol="user_name"
               userCredCol="user_pass"
               userRoleTable="user_roles"
               roleNameCol="role_name">
            <CredentialHandler
                    className="org.apache.catalina.realm.SecretKeyCredentialHandler"
                    algorithm="PBKDF2WithHmacSHA512"
                    keyLength="256"/>
        </Realm>
    </Realm>

    <Resource
            type="javax.sql.DataSource"
            driverClassName="com.mysql.cj.jdbc.Driver"
            name="jdbc/authority"
            auth="Container"
            maxTotal="10"
            maxIdle="2"
            maxWaitMillis="20000"
            removeAbandonedOnBorrow="true"
            removeAbandonedOnMaintenance="true"
            removeAbandonedTimeout="60"
            logAbandoned="true"
            username="username"
            password="password"
            url="url_to_database"
            validationQuery="select 1 from dual"
    />
</Context>
```
**Environment:**
webapp-runner 9.0.11.0
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**Comment by teemu47** [comment]
https://stackoverflow.com/questions/42364354/heroku-webapp-runner-jndi-naming-resource-not-available
