### ISSUE TITLE
Unusual java process hang while using webapp-runner

### ISSUE THREAD

**Issue by toby5box** [jsimone/webapp-runner#147]
I don't think I've encountered this before after years of using xsbt-web-plugin in sbt. I have three `java` processes that aren't responding to signals and one of them is camping on port 8080 so I can't start Tomcat from sbt (`tomcat:start`).

```
$ ps aux|grep java
Toby             19453   0.7  6.6 10213284 1110052 s008  S    11:24am   0:42.63 /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/bin/java -cp /Users/Toby/.ivy2/cache/com.github.jsimone/webapp-runner/jars/webapp-runner-8.5.15.1.jar webapp.runner.launch.Main --port 8080 /Users/Toby/Documents/FiveBox/xx/xx-service/target/webapp
Toby             18269   0.7  1.7 10197376 288884 s008  S     9:57am   0:56.93 /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/bin/java -cp /Users/Toby/.ivy2/cache/com.github.jsimone/webapp-runner/jars/webapp-runner-8.5.15.1.jar webapp.runner.launch.Main --port 8080 /Users/Toby/Documents/FiveBox/xx/xx-service/target/webapp
Toby             19566   0.7  7.2 10196020 1200220 s008  S    11:26am   0:47.39 /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/bin/java -cp /Users/Toby/.ivy2/cache/com.github.jsimone/webapp-runner/jars/webapp-runner-8.5.15.1.jar webapp.runner.launch.Main --port 8080 /Users/Toby/Documents/FiveBox/xx/xx-service/target/webapp
```

There are no wrapping sbt processes running, all have been exited at some point.

I did get a thread dump from one of these `java` processes:

```
$ jstack -l 19453
2019-06-19 12:02:58
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode):

"Attach Listener" #26 daemon prio=9 os_prio=31 tid=0x00007f9884024800 nid=0x5d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"SIGTERM handler" #25 daemon prio=9 os_prio=31 tid=0x00007f988584f800 nid=0x9603 waiting for monitor entry [0x00007000095e3000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x00000006c0024ee0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"SIGTERM handler" #24 daemon prio=9 os_prio=31 tid=0x00007f9886915800 nid=0x5b03 waiting for monitor entry [0x00007000094e0000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x00000006c0024ee0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"SIGTERM handler" #23 daemon prio=9 os_prio=31 tid=0x00007f9884024000 nid=0x5a03 waiting for monitor entry [0x00007000093dd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x00000006c0024ee0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"SIGTERM handler" #22 daemon prio=9 os_prio=31 tid=0x00007f9886043800 nid=0x9803 waiting for monitor entry [0x00007000092da000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x00000006c0024ee0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"SIGTERM handler" #21 daemon prio=9 os_prio=31 tid=0x00007f9886043000 nid=0x5803 waiting for monitor entry [0x00007000091d7000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x00000006c0024ee0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"SIGTERM handler" #20 daemon prio=9 os_prio=31 tid=0x00007f98848f4800 nid=0x9b03 waiting for monitor entry [0x00007000090d4000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x00000006c0024ee0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"SIGTERM handler" #19 daemon prio=9 os_prio=31 tid=0x00007f988109a800 nid=0x9d03 waiting for monitor entry [0x0000700008fd1000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x00000006c0024ee0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"SIGINT handler" #18 daemon prio=9 os_prio=31 tid=0x00007f988480e800 nid=0xa007 waiting for monitor entry [0x0000700008ece000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x00000006c0024ee0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Timer-0" #16 daemon prio=5 os_prio=31 tid=0x00007f988682c800 nid=0xe07 in Object.wait() [0x0000700008cc8000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c093c5f8> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000006c093c5f8> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

   Locked ownable synchronizers:
	- None

"java-sdk-http-connection-reaper" #15 daemon prio=5 os_prio=31 tid=0x00007f9880f58000 nid=0x1107 waiting on condition [0x0000700007580000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.amazonaws.http.IdleConnectionReaper.run(IdleConnectionReaper.java:188)

   Locked ownable synchronizers:
	- None

"Thread-1" #11 prio=5 os_prio=31 tid=0x00007f98801ba800 nid=0x5703 waiting for monitor entry [0x0000700008dcb000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:194)
	- waiting to lock <0x00000006c0032748> (a org.apache.catalina.core.StandardServer)
	at webapp.runner.launch.Main$2.run(Main.java:398)

   Locked ownable synchronizers:
	- None

"SIGTERM handler" #14 daemon prio=9 os_prio=31 tid=0x00007f9880a51800 nid=0xa203 in Object.wait() [0x0000700008bc5000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c00325c8> (a webapp.runner.launch.Main$2)
	at java.lang.Thread.join(Thread.java:1249)
	- locked <0x00000006c00325c8> (a webapp.runner.launch.Main$2)
	at java.lang.Thread.join(Thread.java:1323)
	at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:106)
	at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
	at java.lang.Shutdown.runHooks(Shutdown.java:123)
	at java.lang.Shutdown.sequence(Shutdown.java:167)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- locked <0x00000006c0024ee0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"localhost-startStop-1" #13 daemon prio=5 os_prio=31 tid=0x00007f98820c9000 nid=0xa403 runnable [0x0000700008ac0000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	- locked <0x000000078857f8b8> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	- locked <0x000000078859d6b0> (a sun.security.ssl.AppInputStream)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1297)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2235)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2202)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2191)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeReceiveMessage(AmazonSQSClient.java:1615)
	at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1586)
	at com.xx.service.aws.Sqs.$anonfun$receiveLongPoll$1(Sqs.scala:45)
	at com.xx.service.aws.Sqs$$Lambda$370/1455225022.apply(Unknown Source)
	at scalaz.$bslash$div$.fromTryCatchThrowable(Either.scala:372)
	at com.xx.service.aws.Sqs.receiveLongPoll(Sqs.scala:45)
	at com.xx.service.impl.BouncePoller.pollQueue(BouncePoller.scala:11)
	at com.xx.service.Deploy$$anon$1.<init>(Deploy.scala:222)
	at com.xx.service.Deploy.contextInitialized(Deploy.scala:221)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	- locked <0x00000006c003c020> (a org.apache.catalina.core.StandardContext)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000006c003c020> (a org.apache.catalina.core.StandardContext)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000006c0038ec8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Tomcat-startStop-1" #12 daemon prio=5 os_prio=31 tid=0x00007f98820f3800 nid=0xa603 waiting on condition [0x00007000089bf000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c003ad20> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:939)
	- locked <0x00000006c003ad58> (a org.apache.catalina.core.StandardHost)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	- locked <0x00000006c003ad58> (a org.apache.catalina.core.StandardHost)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000006c003ad58> (a org.apache.catalina.core.StandardHost)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000006c003aee0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007f9881012800 nid=0x5503 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007f9882830800 nid=0x4003 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007f9882828000 nid=0x3e03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007f9880026000 nid=0x3c03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007f988001d000 nid=0x4303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007f9880020000 nid=0x4507 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f988200b800 nid=0x3503 in Object.wait() [0x00007000081a7000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0020760> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c0020760> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f9882817000 nid=0x3303 in Object.wait() [0x00007000080a4000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c003bae8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c003bae8> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
	- None

"main" #1 prio=5 os_prio=31 tid=0x00007f9881003000 nid=0x1803 waiting on condition [0x0000700007686000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c003ae78> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:939)
	- locked <0x00000006c003bcf8> (a org.apache.catalina.core.StandardEngine)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	- locked <0x00000006c003bcf8> (a org.apache.catalina.core.StandardEngine)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000006c003bcf8> (a org.apache.catalina.core.StandardEngine)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	- locked <0x00000006c003bcf8> (a org.apache.catalina.core.StandardEngine)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000006c003be18> (a org.apache.catalina.core.StandardService)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793)
	- locked <0x00000006c003be60> (a java.lang.Object)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000006c0032748> (a org.apache.catalina.core.StandardServer)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:344)
	at webapp.runner.launch.Main.main(Main.java:274)

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=31 tid=0x00007f988200b000 nid=0x4c03 runnable

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007f9883000000 nid=0x2a07 runnable

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007f9882801800 nid=0x2b03 runnable

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007f9883001000 nid=0x2c03 runnable

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007f988100c000 nid=0x5103 runnable

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007f9880000000 nid=0x4f03 runnable

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007f9880001000 nid=0x4e03 runnable

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007f9882802000 nid=0x2e03 runnable

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007f9880001800 nid=0x3003 runnable

"VM Periodic Task Thread" os_prio=31 tid=0x00007f9880800000 nid=0xa803 waiting on condition

JNI global references: 1004
```

Can only really learn that most of the signal handlers are blocked?

Any advice for cleanly exiting these, since TERM and QUIT signals are not being responded to?

**Comment by toby5box** [comment]
The state of `"localhost-startStop-1"` is a bit suspicious. Maybe it should be a daemon thread.

**Comment by toby5box** [comment]
It was even more embarrassing than that. I had miscoded Thread creation so that the endless Thread task was being started in its constructor, i.e. in Tomcat's `contextInitialized` hook, which then never exited. No wonder things were messed up at shutdown time. (In addition fixed the daemon flag.) 

Hope these comments and thread dump might help someone else googling one day.
