### ISSUE TITLE
Location of expanded-war?

### ISSUE THREAD

**Issue by mmoayyed** [jsimone/webapp-runner#57]
I am running a war file on Heroku. My proc file is as such:

```
web:    java $JAVA_OPTS -jar .../webapp-runner.jar --expand-war --port $PORT app.war
```

I see in heroku logs:

```
2016-01-04T19:58:34.392414+00:00 app[web.1]: Expanding idp.war into /app/target/tomcat.31320/webapps/expanded
2016-01-04T19:58:34.392472+00:00 app[web.1]: Adding Context  for /app/target/tomcat.31320/webapps/expanded
```

Which is fine. However, In order for the app to initialize itself correctly, I need to be able to pass an environment variable to the running process, with a value that points to a directory inside the expanded webapp. I am trying to do this via heroku's config vars. 

I am not sure how to find the location of the expanded web app. Is that something that can be determined and passed?

**Comment by jkutner** [comment]
You can actually set the directory to a static path with the `--expanded-dir-name` option. That's probably the best case for you. Then you can set a config var like:

```
$ heroku config:set WAR_DIR="/app/target/webapp"
```

Then put this in your `Procfile`:

```
web: java $JAVA_OPTS -jar .../webapp-runner.jar --expanded-dir-name $WAR_DIR --expand-war --port $PORT app.war
```

But the default will always be `/app/target/tomcat.$PORT/webapps/expanded`. Since you can't put config vars in config vars, you'd have to set this in the `Procfile` with `env`. Probably not best for you.

**Comment by mmoayyed** [comment]
Excellent. I'll give this a try. Would be best to document this also.

**Comment by mmoayyed** [comment]
Doesn't seem like it's working. I did set the config var, and adjusted my Procfile to match yours exactly. Heroku tells me:

```
2016-01-05T08:50:00.654305+00:00 heroku[web.1]: Starting process with command `java -XX:+UseCompressedOops -jar idp-webapp-overlay/target/dependency/webapp-runner.jar --expanded-dir-name /app/target/webapp/idp --expand-war --port 53022 idp-webapp-overlay/target/idp.war`
2016-01-05T08:50:03.054102+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2016-01-05T08:50:03.069520+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx350m -Xss512k -Dfile.encoding=UTF-8
2016-01-05T08:50:03.801060+00:00 app[web.1]: Exception in thread "main" java.io.IOException: Unable to create the directory [/app/target/tomcat.53022/webapps/app/target/webapp/idp]
2016-01-05T08:50:03.801333+00:00 app[web.1]:    at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:115)
2016-01-05T08:50:03.801411+00:00 app[web.1]:    at webapp.runner.launch.Main.main(Main.java:200)
2016-01-05T08:50:04.571518+00:00 heroku[web.1]: Process exited with status 1
2016-01-05T08:50:04.589580+00:00 heroku[web.1]: State changed from starting to crashed
```

The culprit:

```
2016-01-05T08:50:03.801060+00:00 app[web.1]: Exception in thread "main" java.io.IOException: Unable to create the directory [/app/target/tomcat.53022/webapps/app/target/webapp/idp]
```

My config war for `WAR_DIR` is set to `/app/target/webapp/idp`. 

So my var is appended to the default path. That is issue 1. Issue 2, even if that somehow was the correct path, the directly cannot be created.

**Comment by oniseijin** [comment]
This is a major issue for me. Solvable if you could actually use configuration variables inside other configuration variables, or allowing the --expanded-dir-name to be absolute

**Comment by jkutner** [comment]
I would definitely accept a PR for that. Otherwise, will take a look eventually.

**Comment by oniseijin** [comment]
Gave it a round of testing, and worked: "relative" and absolute paths supported and would get converted to absolute path. 

Because I didn't want to fork out ExpandWar.expand, I created a temporary Host object.

**Comment by marcckku** [comment]
Hi, I'am from Italy, i using webapp-runner.jar on my web app. 
I'am using your example from this project -> 
[   https://github.com/kissaten/webapp-runner-minimal  ]  but i costumizing your project and I want to ask you,  in this case,  how to change the tomcat port ??????

**Comment by jkutner** [comment]
@marcckku use the `--port` option

**Comment by marcckku** [comment]
Hi !!
Thank you for your answers
I'm having problems now, however, with my app. My app is created with "Spring 4.3 (MVC modul )" + the runner (tomcat) and distributed on Heroku now without problems. But now I have to implement the rest services along with angular 2 as a frontend.
My problem is that when I run locally with Glassfish the rest services work and angular2 can intercept the data exposed but when I want to run my app from the command line then run the "runner = tomcat", then angular2 can no longer intercept the data.
Question: can I change the "tomcat" runner for a "TomcatEE"? or a Glassfish (application server) ?? ....

**Comment by jkutner** [comment]
No webapp runner does not support TomcatEE.
