### ISSUE TITLE
Unknown option: --scanBootstrapClassPath

### ISSUE THREAD

**Issue by ignatalexeyenko** [jsimone/webapp-runner#63]
Running java -jar ./target/dependency/webapp-runner.jar ${WEBAPP_RUNNER_OPTS:-"--scanBootstrapClassPath"} --port $PORT ./my.war

Throws:

Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: --scanBootstrapClassPath
    at com.beust.jcommander.JCommander.parseValues(JCommander.java:723)
    at com.beust.jcommander.JCommander.parse(JCommander.java:275)
    at com.beust.jcommander.JCommander.parse(JCommander.java:258)
    at com.beust.jcommander.JCommander.<init>(JCommander.java:203)
    at webapp.runner.launch.Main.main(Main.java:70)

EDIT: environment
webapp-runner 7.0.57.2

EDIT#2: environments
Reproduces too in
webapp-runner  8.0.33.1

**Comment by ignatalexeyenko** [comment]
Please cherry-pick https://github.com/jsimone/webapp-runner/commit/686de8765c768208d73cf9145fd4b3172262233b and publish a 7.0 release with ability to scan bootstrap classpath.

**Comment by jkutner** [comment]
I won't backport scanBootstrapClassPath to Tomcat 7, sorry. But it should work in webapp-runner 8.0.33.1. Can you double check that?
